[LAST_UPDATE]
INSTRUMENTS = "20230917"
IDENTITY = "20230917"

[PATH]
TICKERS_DATA = "database/tickers_data"
DATABASE = "database"

[URI]
IDENTITY = "http://cdn.tsetmc.com/api/Instrument/GetInstrumentIdentity/{}"
