[LAST_UPDATE]
INSTRUMENTS = "20230905"
IDENTITY = "20230909"
DAILY_PRICES = "20230909"

[PATH]
TICKERS_DATA = "database/tickers_data"
DATABASE = "database"

[URI]
IDENTITY = "http://cdn.tsetmc.com/api/Instrument/GetInstrumentIdentity/{}"
